### ISSUE TITLE
Homebrew-science deprecated - alternative?

### ISSUE THREAD

**Issue by KEB1** [vsbuffalo/bds-files#11]
Hi Vince,

I'm setting up my first bioinformatics project by working through your book. I have just installed homebrew and then discovered that homebrew-science has been deprecated. Do you have any recommendations for an alternative I could use? I will be working with viral NGS data.

Thanks,

Kate

**Comment by butterflyology** [comment]
Shaun Jackman has started a tap for bioinformatics formula at:
github.com/brewsci/homebrew-bio
He's archived all of the formulae from the Homebrew/science tap at:
[Link](https://t.co/NPXLha1OrS)

TL/DR;
🍺 brew tap brewsci/bio
🍺 brew tap brewsci/science
💀 brew untap homebrew/science

**Comment by KEB1** [comment]
Excellent - thanks very much

**Comment by vsbuffalo** [comment]
Yup this is what I recommend as well — I was surprised that homebrew-science closed but thanks to Shaun Jackman we're still able to leverage homebrew for science packages!
