### ISSUE TITLE
Mistake in Figure 9-2.

### ISSUE THREAD

**Issue by kramasamy90** [vsbuffalo/bds-files#12]
I think there is a mistake in Figure 9-2. In the present Figure 9-2 the ranges [1,5) and [2,5], and [8,9) and [9,9] don't seem to represent the same sequences. I think this because the index should start from 1 in 1-based system as shown in the figure below.

![image](https://user-images.githubusercontent.com/11187209/38997860-6031b2a0-4429-11e8-9832-c58a2de889aa.png)

**Comment by vsbuffalo** [comment]
Yes, thank you. This is a known issue — the book's illustrator accidentally made both sequences start from 1 and I missed this during copyediting. The original figure is here: https://github.com/vsbuffalo/bds-files/blob/master/errata.md
